### ISSUE TITLE
Crash with my modpack

### ISSUE THREAD

**Issue by VanillaSnowGolem** [nonamecrackers2/ender-trigon#8]
https://pastebin.com/rMkkSXxH

**Comment by nonamecrackers2** [comment]
Yeah looks like some sort of compatibility issue, doesn't look like Ender Trigon is doing anything wrong. What other mods do you have installed?

**Comment by VanillaSnowGolem** [comment]
Ok, I'll try to list the latest mods I added as much as I can(I have about 418 mods):
recipes library
dynamical compass
forbidden arcanus
charms
skill cloaks
epic knights
totw modded
travelers backpack
philips ruins
alchemy lib
chemy lib
aeroblender
sculkhorde
alchemistry
ancient manuscripts
recruits

These were mods I added later + with Ender Trigon

**Comment by nonamecrackers2** [comment]
I don't think I'll be able to diagnose the problem with that amount of mods lol. You'll have to go through them and figure out the culprit. I'd recommend looking for mods that may modify the Ender Dragon in any form/capacity.

**Comment by VanillaSnowGolem** [comment]
Hi, so from other sources it turns out there's something genuinely wrong with Ender Trigon itself, specifically for the 1.19.4 version.
According to some other people I mentioned this problem to, it has a very breaking change to the vanilla code.

Something about it wanting to make the dragon fight creation method private when it's not because you can't reduce methods' visibility

this isn't a compatibility error

**Comment by nonamecrackers2** [comment]
I meant to get back to you on CurseForge but I forgot, this is a more appropriate place anyway

This is the method in question:
![image](https://github.com/nonamecrackers2/ender-trigon/assets/105086648/c4e48533-bc94-4503-97e0-4d5a7b4a69d2)

That method is directly from the normal ender dragon, and is private. This is the mixin overwrite the mod uses:
![image](https://github.com/nonamecrackers2/ender-trigon/assets/105086648/abc9880a-3d5b-4728-98bb-e7a5461f2b5f)

This method copies the visiblity of the vanilla one. If I'm not mistaken I shouldn't be reducing the visiblity of the method at all

EDIT: Removed a portion since it was not true (what I sent from the Forge bot was for access transforming)

Have you tried running Ender Trigon by itself to see if the issue persists?

**Comment by VanillaSnowGolem** [comment]
Ok so I tried to use Ender Trigon by itself and it did work. I then decided to put the mods from my modpack one by one until I reach a point where it doesn't work again. This log is the result, can you please figure out some stuff? Thank you.
https://pastebin.com/JTe15bG0

**Comment by nonamecrackers2** [comment]
What was the mod that you put in that caused this crash report?

**Comment by VanillaSnowGolem** [comment]
Based on my testing it seemed to be a mod called Cloud Rider, which btw is a mod that depends on Geckolib.

**Comment by nonamecrackers2** [comment]
Interesting. I'd report the issue to them then, since there shouldn't be anything wrong on my end (unless if there is something on my end, which could totally be the case)
