### ISSUE TITLE
Incompatibility wetween Ender Trigon and Savage Ender Dragon

### ISSUE THREAD

**Issue by Trazyne** [nonamecrackers2/ender-trigon#9]
**Minecraft version**
1.19.2

**Mod version**
1.0 for Ender Trigon and 4.1 for Savage Ender Dragon

**Describe the bug**
Savage Ender Dragon doesn't seem to work at all.
For exemple, the crystals don't respawn, breaking them dont spawn mobs, or the normally disable mob spawn isn't active on the main island

**To Reproduce**
1. Install both mods
2. lunch a world or a server
3. enter the end

**Crash Reports / Logs**
No crash report

**Screenshots**
No screenshot to add.

**Comment by nonamecrackers2** [comment]
I tested this with just the 1.19.2 version of Savage Ender Dragon, and this seems to be the case regardless of whether Ender Trigon is installed or not. The 1.20.1 version seems to have all the features your talking about, so maybe those were added exclusively for that version? If you still think this is a bug I'd report this to Savage Ender Dragon since Ender Trigon seems to be having no effect.
